global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'churn_api'
    scrape_interval: 5s
    static_configs:
      # We now point to the SERVICE NAME defined in docker-compose
      - targets: ['churn-api:8000']